---
# vars/Amazon.yml: Variables for Amazon Linux AMI
# Defaults are defined in defaults/main.yml

# Define repo url without $releasever
# Define epel version to 6 by default, change to 7 when using a version 2 AMI
epel_version: 6
sensu_yum_repo_url: "https://sensu.global.ssl.fastly.net/yum/{{epel_version}}/$basearch/"

# Set this to false to disable the EPEL repo installation
enable_epel_repo: true
epel_repo_rpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{epel_version}}.noarch.rpm"

# RabbitMQ/Erlang
sensu_rabbitmq_repo_version: v3.7.x
sensu_rabbitmq_erlang_repo_version: 20
sensu_rabbitmq_signing_key: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
sensu_rabbitmq_baseurl: "https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/{{ sensu_rabbitmq_repo_version }}/el/{{ epel_version }}"
sensu_rabbitmq_erlang_signing_key: "{{ sensu_rabbitmq_signing_key }}"
sensu_rabbitmq_erlang_baseurl: "https://dl.bintray.com/rabbitmq/rpm/erlang/{{ sensu_rabbitmq_erlang_repo_version }}/el/{{ epel_version }}"
