---
# vars/Debian.yml: Variables for Debian
# Defaults are defined in defaults/main.yml

# redis server properties
redis_pkg_name: redis-server
redis_service_name: redis-server

sensu_erlang_pin_package: 'esl-erlang erlang*'
sensu_erlang_pin_version: '1:20.3*'
sensu_rabbitmq_signing_key: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
sensu_rabbitmq_repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
sensu_rabbitmq_erlang_signing_key: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
sensu_rabbitmq_erlang_repo: "deb https://packages.erlang-solutions.com/debian {{ ansible_distribution_release }} contrib"
