---
# tasks/Ubuntu/main.yml: Ubuntu specific set-up
# This takes care of base prerequisites for Ubuntu

- include_vars: "{{ ansible_distribution }}.yml"

- name: Ensure that https transport is ready
  apt:
    name: apt-transport-https
    state: present
    cache_valid_time: 3600
    update_cache: true

- name: Ensure the Sensu APT repo GPG key is present
  apt_key:
    url: "{{ sensu_apt_key_url }}"
    state: present

- name: Ensure the Sensu Core APT repo is present
  apt_repository:
    repo: "{{ sensu_apt_repo_url }}"
    state: present
    update_cache: true

- name: Ensure Sensu is installed
  apt:
    name: "{{ sensu_package }}"
    state: "{{ sensu_pkg_state }}"
