---
# tasks/SmartOS/server.yml: Deploy the necessary configuration for
# a Sensu 'master' node.
# Specific to SmartOS

- include_vars: "{{ ansible_distribution }}.yml"

- name: Deploy Sensu server service manifest
  template:
    dest: /opt/local/lib/svc/manifest/sensu-server.xml
    src: sensu-server.smartos_smf_manifest.xml.j2
    owner: root
    group: root
    mode: 0644
  notify: import sensu-server service

- name: Deploy Sensu API service manifest
  template:
    dest: /opt/local/lib/svc/manifest/sensu-api.xml
    src: sensu-api.smartos_smf_manifest.xml.j2
    owner: root
    group: root
    mode: 0644
  notify: import sensu-api service

- meta: flush_handlers
